# EXAMPLE file which does NOT enables LUKS encryption
# 
# Secrets file used to hold sensitive date that can be substituted into the user-data and / or brtfs-fstab file.  The file format is yaml.
#       The presence of a luks_passphase secret_name will enable encryption.  For example:
#           luks_passphrase : test123
#       The luks_passphrase secret_name must be called "luks_passphrase".  All other secret_names are user configurable
#       If there is no line containing "luks_passphrase", the disk will not be encrypted.
#
secrets:
 - host_name : host1
 - user_name : user1
 - user_password : test123
 - client1_pub_key : ssh-rsa AAAA... user@client1
 - client2_pub_key : ssh-rsa AAAA... user@client2
 - public_key : ssh-rsa AAAA...user1@host
 - private_key : |
      -----BEGIN OPENSSH PRIVATE KEY-----
         ...
          -----END OPENSSH PRIVATE KEY-----
 - luks_passphrase : test
 - dropbear_pub_key : ssh-rsa AAAA... user@client
